# Generated by Django 4.1.7 on 2023-02-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performer', '0002_alter_performer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performer.performer')),
            ],
        ),
    ]
